# aretext configuration

# Each rule below defines a pattern to match the file path.
# All matching rules are merged in-order, with configuration from
# later rules replacing or extending configurations from prior rules.
#
# Customization guide: https://aretext.org/docs/customization.html
# Configuration reference: https://aretext.org/docs/config-reference.html

- name: default
  pattern: "**"
  config:
    autoIndent: false
    hideDirectories:
      - "**/.git"
      - "**/.cache"
      - "**/.local"
      - "**/.rustup"
      - "**/go/pkg/mod"
      - "**/venv"
      - "**/.kube/cache"
    syntaxLanguage: plaintext
    tabExpand: false
    tabSize: 4
    showTabs: false
    showLineNumbers: false
    styles:
      lineNum: {color: "olive"}
      tokenOperator: {color: "purple"}
      tokenKeyword: {color: "olive"}
      tokenNumber: {color: "green"}
      tokenString: {color: "maroon"}
      tokenComment: {color: "navy"}
      tokenCustom1: {color: "teal"}
      tokenCustom2: {color: "fuchsia"}
      tokenCustom3: {color: "red"}
      tokenCustom4: {color: "lime"}
      tokenCustom5: {color: "aqua"}
      tokenCustom6: {color: "darkgreen"}
      tokenCustom7: {color: "darkcyan"}
      tokenCustom8: {color: "darkblue"}
    menuCommands:
      - name: strip trailing whitespace
        shellCmd: sed -i 's/[ \t]*$//' "$FILEPATH"
        mode: silent
      - name: git blame
        shellCmd: git blame "$FILEPATH" | less +$LINE
      - name: git commit wip
        shellCmd: git add -u && git commit -m 'wip'
        save: true

- name: tmux clipboard commands
  pattern: "**"
  config:
    menuCommands:
    - name: copy to clipboard
      shellCmd: printenv SELECTION | tmux load-buffer -
      mode: silent
    - name: paste from clipboard
      shellCmd: tmux show-buffer
      mode: insert

- name: tmux window commands
  pattern: "**"
  config:
    menuCommands:
    - name: split window horizontal
      shellCmd: tmux split-window -h "aretext $FILEPATH"
      mode: silent
    - name: split window vertical
      shellCmd: tmux split-window -v "aretext $FILEPATH"
      mode: silent

- name: grep command
  pattern: "**"
  config:
    menuCommands:
      - name: grep word
        shellCmd: rg $WORD --vimgrep
        mode: fileLocations

- name: git commit
  pattern: "**/.git/COMMIT_EDITMSG"
  config:
    syntaxLanguage: gitcommit

- name: git rebase
  pattern: "**/.git/**/git-rebase-todo"
  config:
    syntaxLanguage: gitrebase

- name: json
  pattern: "**/*.json"
  config:
    autoIndent: true
    syntaxLanguage: json
    tabExpand: true
    tabSize: 2
    showLineNumbers: true

- name: yaml
  pattern: "**/*.yaml"
  config: &yamlConfig
    autoIndent: true
    syntaxLanguage: yaml
    tabExpand: true
    tabSize: 2
    showLineNumbers: true

- name: yml
  pattern: "**/*.yml"
  config: *yamlConfig

- name: sh
  pattern: "**/*.sh"
  config:
    autoIndent: true
    tabExpand: true
    tabSize: 4
    showLineNumbers: true

- name: html
  pattern: "**/*.html"
  config:
    autoIndent: true
    tabExpand: true
    tabSize: 2
    showLineNumbers: true

- name: css
  pattern: "**/*.css"
  config:
    autoIndent: true
    tabExpand: true
    tabSize: 2
    showLineNumbers: true

- name: Makefile
  pattern: "**/Makefile"
  config:
    showTabs: true
    tabExpand: false
    autoIndent: true
    tabSize: 4
    showLineNumbers: true

- name: go
  pattern: "**/*.go"
  config:
    autoIndent: true
    syntaxLanguage: go
    tabExpand: false
    tabSize: 4
    showLineNumbers: true
    menuCommands:
    - name: comment or uncomment selection
      shellCmd: printenv SELECTION | ~/.config/aretext/scripts/comment-go.py
      mode: insert
    - name: insert test snippet
      shellCmd: cat ~/.config/aretext/snippets/go-test.go
      mode: insert
    - name: gospelunk index
      shellCmd: ~/.config/aretext/scripts/gospelunk-index-file.py "$FILEPATH" | less
    - name: gospelunk find
      shellCmd: ~/.config/aretext/scripts/gospelunk-find-file.py "$WORD" "$FILEPATH"
      mode: fileLocations

- name: python
  pattern: "**/*.py"
  config:
    autoIndent: true
    syntaxLanguage: python
    tabExpand: true
    tabSize: 4
    showLineNumbers: true

- name: rust
  pattern: "**/*.rs"
  config:
    autoIndent: true
    syntaxLanguage: rust
    tabExpand: true
    tabSize: 4
    showLineNumbers: true

- name: c
  pattern: "**/*.c"
  config: &cconfig
    autoIndent: true
    syntaxLanguage: c
    tabExpand: true
    tabSize: 4
    showLineNumbers: true

- name: c-header
  pattern: "**/*.h"
  config: *cconfig

- name: protobuf
  pattern: "**/*.proto"
  config:
    autoIndent: true
    syntaxLanguage: protobuf
    tabExpand: true
    tabSize: 2
    showLineNumbers: true

- name: markdown
  pattern: "**/*.md"
  config:
    autoIndent: true
    tabExpand: true
    tabSize: 4
    showLineNumbers: true

- name: todo
  pattern: "**/*.todo"
  config: &todotxt
    autoIndent: true
    syntaxLanguage: todotxt
    tabExpand: true
    tabSize: 4
    showLineNumbers: true

- name: devlog-todo
  pattern: "**/devlogs/todo.txt"
  config:
    <<: *todotxt
    menuCommands:
      - name: devlog tidy
        shellCmd: devlog.py tidy
        save: true
        mode: silent

- name: devlog-done
  pattern: "**/devlogs/done.txt"
  config: *todotxt

- name: devlog-git
  pattern: "**/repos/devlog/**"
  config:
    autoIndent: true
    hideDirectories:
    - "**/target"

- name: aretext
  pattern: "**/aretext/**"
  config:
    menuCommands:
    - name: build
      shellCmd: make build | less
      save: true
    - name: test
      shellCmd: make test | less
      save: true
    - name: fmt all
      shellCmd: make fmt
      save: true

- name: aretext-go
  pattern: "**/aretext/**/*.go"
  config:
    menuCommands:
    - name: fmt file
      shellCmd: goimports -w -local "github.com/aretext" $FILEPATH | less
      save: true

- name: aretext-markdown
  pattern: "**/aretext/**/*.md"
  config:
    menuCommands:
    - name: fmt file
      shellCmd: markdownfmt -w $FILEPATH
      save: true

- name: gospelunk-go
  pattern: "**/gospelunk/**/*.go"
  config:
    menuCommands:
    - name: fmt file
      shellCmd: goimports -w $FILEPATH | less
      save: true

- name: gopath
  pattern: "**/go/src/**/*.go"
  config:
    menuCommands:
      - name: fmt file
        shellCmd: goimports -w $FILEPATH | less

- name: kubernetes
  pattern: "**/kubernetes/**"
  config:
    hideDirectories:
      - "**/_output"
